In [1]:
import numpy as np

In [2]:
identidad = np.eye(4)

In [3]:
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
vector = np.array([[2],[3],[5],[7]])


In [8]:
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [9]:
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [10]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [11]:
inversa_A = np.linalg.inv(A)

In [12]:
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [13]:
print(A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
