In [1]:
import numpy as np

escalar = 5.678
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [2]:
A = vector + matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [3]:
A = matriz.T + vector
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [4]:
print(vector)

[3 4 5]


In [5]:
print(matriz.T)

[[1 3 5]
 [2 4 6]]


In [6]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
#Esto se le llama broadcasting donde el vector se
#extiende para completar con la del mayor dimencion
C = matriz + 42
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [8]:
D = matriz + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]
