In [8]:
import numpy as np
escalar = 5.678
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]],
])

In [9]:
escalar_t = escalar.T

AttributeError: 'float' object has no attribute 'T'

In [10]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [11]:
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [12]:
print(matriz.shape)

(3, 2)


In [13]:
print(matriz_t.shape)

(2, 3)


In [14]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [16]:
print(tensor)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


In [17]:
matriz_t_t = matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
#Una matriz se puede sumar unicamente si tienen
#Las mismas dimenciones

In [19]:
A = matriz
B = matriz_t

In [20]:
C = A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [23]:
A = np.array([[3,4],[7,8],[12,9]])
B = np.array([[4,3],[5,6],[14,7]])
C = A+B
print(A)
print("--------------")
print(B)
print("--------------")
print(C)



[[ 3  4]
 [ 7  8]
 [12  9]]
--------------
[[ 4  3]
 [ 5  6]
 [14  7]]
--------------
[[ 7  7]
 [12 14]
 [26 16]]


In [24]:
D = matriz + escalar
print(D)

[[ 6.678  7.678]
 [ 8.678  9.678]
 [10.678 11.678]]
